### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by zeke** [circularone/rp-updates#1]
Hello @circularone. 👋 

I saw this app show up with a 404 HTTP response in the request logs for update.electronjs.org. Please let me know if you're having any trouble with the service.

**Comment by circularone** [comment]
Hi zeke, thanks. I'm having trouble getting updates to work on Windows, it works fine on mac. I've code signed the Windows version using a standard certificate.

The app is in a private repo and i'm setting the repo to this public one using

`require('update-electron-app')({
  repo: 'circularone/rp-updates',
  logger: require('electron-log')
})`

But the 404 makes me think that isn't being picked up on Windows

**Comment by circularone** [comment]
Hi zeke, could you please post the 404 details?

**Comment by zeke** [comment]
```
May 16 21:34:32 electron-update-server app/web.1: {"level":30,"time":1526531672477,"msg":"request","pid":4,"hostname":"1beeea34-e576-4153-befb-93e58fa34045","method":"GET","url":"/circularone/rp-updates/darwin/0.9.4","status":404,"ipHash":"b11634f2e3597d1fa2e2b37d2f8599ad4c4994bbd7ba9e46f7f6eb1e407eb452","duration":2,"v":1} 
```

**Comment by circularone** [comment]
Thanks zeke, awesome of you to comment out of the blue offering help :star:

**Comment by zeke** [comment]
Hey @circularone. Just FYI we're still seeing lots of request to this URL in the logs:

> https://update.electronjs.org/circularone/rp-updates/darwin/0.9.4

The status for that is 404 and the response is

> No updates found (needs asset matching *{mac,darwin,osx}*.zip in public repository)

**Comment by circularone** [comment]
Thanks @zeke, you should see them disappear (if they haven't already). We switched to using github directly and it's all working fine now.
